name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '30 11 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Medium Blog
        # - uses: actions/checkout@v2
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/@snehapatil1"
